### ISSUE TITLE
Make Error on OSX

### ISSUE THREAD

**Issue by teafella** [schazers/cs148-student-repo#2]
Latest commit breaks building on OSX for me.

My make command breaks on:
`cs148-student-repo/lib/glew/include/GL/eglew.h:106:10: fatal error: 'KHR/khrplatform.h' file not found`

This is fixed if I check out an earlier version

**Comment by DABH** [comment]
My bad -- OS X is based on Unix so the UNIX CMake variable is also TRUE in OS X environments, not just Linux -- hence the Linux fixes were unintentionally being applied on OS X (causing errors).  I have pushed a fix for this.  Would you mind cloning and building a fresh copy of the starter code, to see if it's all good on OS X again with the latest commit?  Many thanks!

**Comment by teafella** [comment]
Just tested it, works great now!
